name: dem3d
channels:
  - conda-forge
dependencies:
  - voila
  - nbserverproxy
  - ipyleaflet
  - xarray
  - xarray-simlab
  - fastscape
  - ipygany
  - matplotlib
  - gdal
  - zarr
  - requests
  - tqdm
